// flow-typed signature: 47a00addef87e2f93b06221e29d67c8d
// flow-typed version: <<STUB>>/drivelist_v^5.0.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'drivelist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'drivelist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'drivelist/example' {
  declare module.exports: any;
}

declare module 'drivelist/lib/drivelist' {
  declare module.exports: any;
}

declare module 'drivelist/lib/parse' {
  declare module.exports: any;
}

declare module 'drivelist/lib/scripts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'drivelist/example.js' {
  declare module.exports: $Exports<'drivelist/example'>;
}
declare module 'drivelist/lib/drivelist.js' {
  declare module.exports: $Exports<'drivelist/lib/drivelist'>;
}
declare module 'drivelist/lib/parse.js' {
  declare module.exports: $Exports<'drivelist/lib/parse'>;
}
declare module 'drivelist/lib/scripts.js' {
  declare module.exports: $Exports<'drivelist/lib/scripts'>;
}
