// flow-typed signature: 27e764c28d8b446339d0e30c93b1816d
// flow-typed version: <<STUB>>/electron-compile_v^6.1.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-compile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-compile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-compile/lib/browser-signal' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/cli' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/compile-cache' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/compiler-host' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/config-parser' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/custom-operators' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/digest-for-object' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/es6-shim' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/file-change-cache' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/for-all-files' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/index' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/initialize-renderer' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/live-reload' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/packager-cli' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/pathwatcher-rx' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/promise' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/protocol-hook' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/read-only-compiler' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/require-hook' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/rig-mime-types' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/sanitize-paths' {
  declare module.exports: any;
}

declare module 'electron-compile/lib/x-require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-compile/lib/browser-signal.js' {
  declare module.exports: $Exports<'electron-compile/lib/browser-signal'>;
}
declare module 'electron-compile/lib/cli.js' {
  declare module.exports: $Exports<'electron-compile/lib/cli'>;
}
declare module 'electron-compile/lib/compile-cache.js' {
  declare module.exports: $Exports<'electron-compile/lib/compile-cache'>;
}
declare module 'electron-compile/lib/compiler-host.js' {
  declare module.exports: $Exports<'electron-compile/lib/compiler-host'>;
}
declare module 'electron-compile/lib/config-parser.js' {
  declare module.exports: $Exports<'electron-compile/lib/config-parser'>;
}
declare module 'electron-compile/lib/custom-operators.js' {
  declare module.exports: $Exports<'electron-compile/lib/custom-operators'>;
}
declare module 'electron-compile/lib/digest-for-object.js' {
  declare module.exports: $Exports<'electron-compile/lib/digest-for-object'>;
}
declare module 'electron-compile/lib/es6-shim.js' {
  declare module.exports: $Exports<'electron-compile/lib/es6-shim'>;
}
declare module 'electron-compile/lib/file-change-cache.js' {
  declare module.exports: $Exports<'electron-compile/lib/file-change-cache'>;
}
declare module 'electron-compile/lib/for-all-files.js' {
  declare module.exports: $Exports<'electron-compile/lib/for-all-files'>;
}
declare module 'electron-compile/lib/index.js' {
  declare module.exports: $Exports<'electron-compile/lib/index'>;
}
declare module 'electron-compile/lib/initialize-renderer.js' {
  declare module.exports: $Exports<'electron-compile/lib/initialize-renderer'>;
}
declare module 'electron-compile/lib/live-reload.js' {
  declare module.exports: $Exports<'electron-compile/lib/live-reload'>;
}
declare module 'electron-compile/lib/packager-cli.js' {
  declare module.exports: $Exports<'electron-compile/lib/packager-cli'>;
}
declare module 'electron-compile/lib/pathwatcher-rx.js' {
  declare module.exports: $Exports<'electron-compile/lib/pathwatcher-rx'>;
}
declare module 'electron-compile/lib/promise.js' {
  declare module.exports: $Exports<'electron-compile/lib/promise'>;
}
declare module 'electron-compile/lib/protocol-hook.js' {
  declare module.exports: $Exports<'electron-compile/lib/protocol-hook'>;
}
declare module 'electron-compile/lib/read-only-compiler.js' {
  declare module.exports: $Exports<'electron-compile/lib/read-only-compiler'>;
}
declare module 'electron-compile/lib/require-hook.js' {
  declare module.exports: $Exports<'electron-compile/lib/require-hook'>;
}
declare module 'electron-compile/lib/rig-mime-types.js' {
  declare module.exports: $Exports<'electron-compile/lib/rig-mime-types'>;
}
declare module 'electron-compile/lib/sanitize-paths.js' {
  declare module.exports: $Exports<'electron-compile/lib/sanitize-paths'>;
}
declare module 'electron-compile/lib/x-require.js' {
  declare module.exports: $Exports<'electron-compile/lib/x-require'>;
}
