// flow-typed signature: eee9f525fc3bbaaf6588f45fd4743a87
// flow-typed version: <<STUB>>/progress-stream_v^1.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'progress-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'progress-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'progress-stream/test/http' {
  declare module.exports: any;
}

declare module 'progress-stream/test/request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'progress-stream/index' {
  declare module.exports: $Exports<'progress-stream'>;
}
declare module 'progress-stream/index.js' {
  declare module.exports: $Exports<'progress-stream'>;
}
declare module 'progress-stream/test/http.js' {
  declare module.exports: $Exports<'progress-stream/test/http'>;
}
declare module 'progress-stream/test/request.js' {
  declare module.exports: $Exports<'progress-stream/test/request'>;
}
