// flow-typed signature: 5114b829ac26ed1b14b7a8d8d6726ff3
// flow-typed version: <<STUB>>/react-resize-detector_v^0.3.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-resize-detector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-resize-detector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-resize-detector/example/containers/App' {
  declare module.exports: any;
}

declare module 'react-resize-detector/example/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-resize-detector/example/index' {
  declare module.exports: any;
}

declare module 'react-resize-detector/example/server' {
  declare module.exports: any;
}

declare module 'react-resize-detector/example/webpack.config' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/components/ResizeDetector' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/helpers/resizeDetectorStyles' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-resize-detector/example/containers/App.js' {
  declare module.exports: $Exports<'react-resize-detector/example/containers/App'>;
}
declare module 'react-resize-detector/example/dist/bundle.js' {
  declare module.exports: $Exports<'react-resize-detector/example/dist/bundle'>;
}
declare module 'react-resize-detector/example/index.js' {
  declare module.exports: $Exports<'react-resize-detector/example/index'>;
}
declare module 'react-resize-detector/example/server.js' {
  declare module.exports: $Exports<'react-resize-detector/example/server'>;
}
declare module 'react-resize-detector/example/webpack.config.js' {
  declare module.exports: $Exports<'react-resize-detector/example/webpack.config'>;
}
declare module 'react-resize-detector/lib/components/ResizeDetector.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/components/ResizeDetector'>;
}
declare module 'react-resize-detector/lib/helpers/resizeDetectorStyles.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/helpers/resizeDetectorStyles'>;
}
declare module 'react-resize-detector/lib/index.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/index'>;
}
