// flow-typed signature: 0359b870698ff4eb56b765fc029f2c2d
// flow-typed version: <<STUB>>/react-shortcuts_v^1.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-shortcuts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-shortcuts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-shortcuts/lib/component/index' {
  declare module.exports: any;
}

declare module 'react-shortcuts/lib/component/shortcuts' {
  declare module.exports: any;
}

declare module 'react-shortcuts/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-shortcuts/lib/index' {
  declare module.exports: any;
}

declare module 'react-shortcuts/lib/shortcut-manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-shortcuts/lib/component/index.js' {
  declare module.exports: $Exports<'react-shortcuts/lib/component/index'>;
}
declare module 'react-shortcuts/lib/component/shortcuts.js' {
  declare module.exports: $Exports<'react-shortcuts/lib/component/shortcuts'>;
}
declare module 'react-shortcuts/lib/helpers.js' {
  declare module.exports: $Exports<'react-shortcuts/lib/helpers'>;
}
declare module 'react-shortcuts/lib/index.js' {
  declare module.exports: $Exports<'react-shortcuts/lib/index'>;
}
declare module 'react-shortcuts/lib/shortcut-manager.js' {
  declare module.exports: $Exports<'react-shortcuts/lib/shortcut-manager'>;
}
