// flow-typed signature: 33e0f18ef6f847a0dc18edb7eb33a334
// flow-typed version: <<STUB>>/trash_v^4.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'trash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trash/lib/linux' {
  declare module.exports: any;
}

declare module 'trash/lib/macos' {
  declare module.exports: any;
}

declare module 'trash/lib/win' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trash/index' {
  declare module.exports: $Exports<'trash'>;
}
declare module 'trash/index.js' {
  declare module.exports: $Exports<'trash'>;
}
declare module 'trash/lib/linux.js' {
  declare module.exports: $Exports<'trash/lib/linux'>;
}
declare module 'trash/lib/macos.js' {
  declare module.exports: $Exports<'trash/lib/macos'>;
}
declare module 'trash/lib/win.js' {
  declare module.exports: $Exports<'trash/lib/win'>;
}
