/* APP */
export const APP_CHANGE_PATH = 'APP_CHANGE_PATH'

/* CONFIG */
export const APP_TOGGLE_EDIT_MODE = 'APP_TOGGLE_EDIT_MODE'

/* NAVBAR */
export const NAVBAR_SELECTION_CHANGED = 'NAVBAR_SELECTION_CHANGED'
export const NAVBAR_HIDE_GROUP = 'NAVBAR_HIDE_GROUP'
export const NAVBAR_REMOVE_GROUP_ITEM = 'NAVBAR_REMOVE_GROUP_ITEM'
export const NAVBAR_CHANGE_GROUP_TITLE = 'NAVBAR_CHANGE_GROUP_TITLE'
export const NAVBAR_NEW_GROUP = 'NAVBAR_NEW_GROUP'
export const NAVBAR_NEW_GROUP_ITEM = 'NAVBAR_NEW_GROUP_ITEM'

/* COUNTER */
export const COUNTER_INCREMENT = 'INCREMENT_COUNTER'
export const COUNTER_DECREMENT = 'DECREMENT_COUNTER'

export const COUNTER_REQUEST_VALUE = 'COUNTER_REQUEST_VALUE'
export const COUNTER_RECEIVE_VALUE = 'COUNTER_RECEIVE_VALUE'

/* FILESYSTEM */
export const FS_WATCHER_READING = 'FS_WATCHER_READING'
export const FS_WATCHER_READY = 'FS_WATCHER_READY'
export const FS_WATCHER_CLOSE = 'FS_WATCHER_CLOSE'
export const FS_ADD = 'FS_ADD'
export const FS_UNLINK = 'FS_UNLINK'
export const FS_CHANGE = 'FS_CHANGE'
