/* APP */
export const APP_CHANGE_PATH = 'APP_CHANGE_PATH'

/* NAVBAR */
export const NAVBAR_SELECTION_CHANGED = 'NAVBAR_SELECTION_CHANGED'
export const NAVBAR_GROUP_NAME_CHANGED = 'NAVBAR_GROUP_NAME_CHANGED'
export const NAVBAR_HIDE_GROUP = 'NAVBAR_HIDE_GROUP'
export const NAVBAR_REMOVE_GROUP_ITEM = 'NAVBAR_REMOVE_GROUP_ITEM'
export const NAVBAR_NEW_GROUP = 'NAVBAR_NEW_GROUP'
export const NAVBAR_NEW_GROUP_ITEM = 'NAVBAR_NEW_GROUP_ITEM'

/* COUNTER */
export const COUNTER_INCREMENT = 'INCREMENT_COUNTER'
export const COUNTER_DECREMENT = 'DECREMENT_COUNTER'

export const COUNTER_REQUEST_VALUE = 'COUNTER_REQUEST_VALUE'
export const COUNTER_RECEIVE_VALUE = 'COUNTER_RECEIVE_VALUE'
