export const COUNTER_INCREMENT = 'INCREMENT_COUNTER'
export const COUNTER_DECREMENT = 'DECREMENT_COUNTER'

export const COUNTER_REQUEST_VALUE = 'COUNTER_REQUEST_VALUE'
export const COUNTER_RECEIVE_VALUE = 'COUNTER_RECEIVE_VALUE'
